remote_theme: CaptainIRS/hacker-plus-theme

title:
author:
description: 
disqus_forum_shortname:
google_site_verification_content: # The 'content' tag for site verification
google_analytics: # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: 1142950 
thm_badge_no: 1016988 
show_thm_htb_badges_in_nav: true
github_username: Inj3c7i0n
gitlab:
medium: inj3c7i0nsec
stackoverflow: users/21770718
hacker_news: 
linkedin: inj3c7i0n-mattmcd/
twitch: inj3c7i0nsec
youtube:
twitter: Inj3c7i0nSec
facebook:
instagram:
reddit:
pinterest:
telegram: Inj3c7i0n
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true